/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment_1;

public class App {
    public String getMessage() {
        return "You can use this file to run the functions of SqlRunnerAPI.java";
    }

    public static void main(String[] args) {
        System.out.println(new App().getMessage());
    }
}
